[package]
name = "kitsune-shim"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
urlencoding = "2.1"
anyhow = "1.0"
open = "5.1"
dirs = "6"
